bag_product_price_locator = "//div[@class='shelf-item__price']//p"
bag_product_name_locator = "//p[@class='title' and text()='PRODUCT_NAME']"
bag_subtotal_locator = "//p[@class='sub-price__val']"
bag_product_desc_locator = "//p[@class='title' and text()='PRODUCT_NAME']/following-sibling::p"
bag_product_plus_locator = "//p[@class='title' and text()='PRODUCT_NAME']/ancestor::div[@class='shelf-item__details']/following-sibling::div[@class='shelf-item__price']//button[.='+']"
bag_product_minus_locator = "//p[@class='title' and text()='PRODUCT_NAME']/ancestor::div[@class='shelf-item__details']/following-sibling::div[@class='shelf-item__price']//button[.='-']"
bag_delete_product_locator = "//p[@class='title' and text()='PRODUCT_NAME']/ancestor::div[@class='shelf-item__details']/preceding-sibling::div[@class='shelf-item__del']"
bag_quantity_locator = "//span[@class='bag__quantity']"
bag_checkout_locaotor = "//div[text()='Checkout']"
